### ISSUE TITLE
writing bytes

### ISSUE THREAD

**Issue by vortexkd** [philipperemy/japanese-words-to-vectors#1]
Using python 3.5, errors such as AttributeError: 'str' object has no attribute 'decode' are thrown.
changing file read and write modes from r to rb, and w to wb respectively fixes the issue.
Thanks for the great work!

**Comment by philipperemy** [comment]
Thanks a lot @vortexkd 

Would you mind crafting a very quick PR?

Thanks again for the help :)

**Comment by philipperemy** [comment]
Fixed with #2 
Thanks a lot!
