### ISSUE TITLE
Input file to generate_vectors

### ISSUE THREAD

**Issue by tringn** [philipperemy/japanese-words-to-vectors#6]
Hi @philipperemy,
Thanks for your great work.
I have a question about the input for function _generate_vector_.
I suppose the input for this function should be tokenized, but I see in the script you are using _JA_WIKI_SENTENCES_FILENAME_, which is not tokenized.
Can you clear my confusion?
Thank you so much.

**Comment by philipperemy** [comment]
@tringn Thank you! I wrote this code long time ago and it seems that the input of the function is an input that needs not be tokenized but it should have one line per sentence: https://radimrehurek.com/gensim/models/word2vec.html#gensim.models.word2vec.LineSentence

**Comment by philipperemy** [comment]
https://github.com/philipperemy/japanese-words-to-vectors/blob/0a5107f37bf4ed3432c127bea0fc1eb886b4845a/generate_vectors.py#L81

**Comment by philipperemy** [comment]
But I agree there is something I quite dont get it. It should go inside the tokenizer at some point and here it does not. I ll investigate more.

**Comment by philipperemy** [comment]
You were correct. I updated the code. Tell me if it looks good to you now. https://github.com/philipperemy/japanese-words-to-vectors/commit/b9e47ee977cd930e3b3e310a83017149d3336a19

**Comment by philipperemy** [comment]
I'll close this as it has been solved.

**Comment by tringn** [comment]
Thank you so much. 
It is clear now.

**Comment by philipperemy** [comment]
@tringn Happy I could help! Good luck ;)
